name: Build & Test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    APP_MODE: "ci"

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: DCC-BS/ci-workflows/actions/node-bun-biome-playwright@52f8293531f9389c887c7d14c2b57d90d12ef9ae # v9
              with:
                  node_version: "24.x"
                  working_directory: "."
                  run_biome: "true"
                  run_playwright: "false"
                  install_method: "bun"
                  build_command: "bun run build"
            - name: test
              run: bun run test:coverage
