name: Build & Test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    APP_MODE: "ci"

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: DCC-BS/ci-workflows/actions/node-bun-biome-playwright@d56b755ec3877da25146ac5f34a2b4003ff6339d # v8
              with:
                  node_version: "24.x"
                  working_directory: "."
                  run_biome: "true"
                  run_playwright: "false"
                  install_method: "bun"
                  build_command: "bun run build"
            - name: test
              run: bun run test
