name: Build & Test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    APP_MODE: "ci"
    CI: true

jobs:
    frontend-ci:
        uses: DCC-BS/ci-workflows/.github/workflows/ci.yml@c78eccc843c19ba40a4b55aa4f4a8537cc3160b3 #v10
