name: Build and Publish Docker Image
on:
    workflow_dispatch:

permissions:
    contents: write
    packages: write

jobs:
    publish:
        uses: DCC-BS/ci-workflows/.github/workflows/publish-docker.yml@52f8293531f9389c887c7d14c2b57d90d12ef9ae # v9
        secrets: inherit
        with:
            registry: ghcr.io
            image_name: ghcr.io/${{ github.repository }}
            context: .
            dockerfile: ./Dockerfile
            platforms: linux/amd64
            push: true
