name: Documentation on demand
on:
  issue_comment:
    types: [ created ]

jobs:
  docs:
    uses: DCC-BS/ci-workflows/.github/workflows/llm-doc-update-conditional.yml@v9
    with:
      doc_repo: "DCC-BS/documentation"
      doc_path: "markdown/nuxt-layers"
      openai_model: GLM-5.1
      openai_base_url: https://api.z.ai/api/coding/paas/v4
      pr_number: ${{ github.event.issue.number }}
      client_id: ${{ vars.DOC_CLIENT_ID }}
    secrets:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      DOC_APP_PRIVATE_KEY: ${{ secrets.DOC_APP_PRIVATE_KEY }}